[project]
name = "daily-arxiv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arxiv>=2.1.3",
    "dotenv>=0.9.9",
    "openai>=1.75.0",
    "scrapy>=2.12.0",
]
